#
# Module manifest for module 'DictionaryFile'
#
# Generated by: Stephanos Constantinou
#
# Generated on: 24/09/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DictionaryFile.psm1'

# Version number of this module.
ModuleVersion = '2.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '2d4cc1fc-c125-4272-a044-df175efc0a6c'

# Author of this module
Author = 'Stephanos Constantinou'

# Company or vendor of this module
CompanyName = 'sconstantinou.com'

# Copyright statement for this module
Copyright = '(c) 2018 Stephanos Constantinou. All rights reserved.'

# Description of the functionality provided by this module
Description = 'DictionaryFile module will create all password combinations that you are able to have
using a specific characterset. Using this module you will be able to find number of all
password combinations. You are able to create the combinations either on the screen or
use them with another cmdlet. Also, you are able to create a dictionary file including
generated passwords and import a dictionary file that you have already created.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-PasswordNumber','Get-PasswordCombination','Get-DictionaryFile','New-DictionaryFile'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'gpn','gpc','gdf','ndf'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'DictionaryFile.psd1', 'DictionaryFile.psm1'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Password','Generator','Dictionary','BruteForce','Security','Penetration','Combinations','Permutations'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/SConstantinou/DictionaryFile/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/SConstantinou/DictionaryFile'

        # A URL to an icon representing this module.
        IconUri = 'https://www.sconstantinou.com/sconstantinou_website_logo_small_publisher/'

        # ReleaseNotes of this module
        ReleaseNotes = '2.0 24-09-2018
* Add Get-PasswordCombination
* Add New-DictionaryFile
* Replace Get-DictionaryFile
* Add Input from Pipiline
* Add Ouput to Pipeline
* Characters parameter removed
* Numbers parameter removed
* Symbols parameter removed
* CharacterSet parameter added
* Code Improvements

1.0 13-09-2018
* Initial Realease'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

